# Supabase Site Visits Table Setup

-- Create the table
CREATE TABLE site_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  path TEXT NOT NULL,
  referrer TEXT,
  user_agent TEXT,
  ip TEXT,
  country TEXT,
  city TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE site_visits ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anonymous inserts (for the visitor logger)
CREATE POLICY "Enable insert for anonymous users" ON site_visits
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Create a policy that allows authenticated users to view the data (for your dashboard)
CREATE POLICY "Enable read access for authenticated users only" ON site_visits
  FOR SELECT
  TO authenticated
  USING (true);

-- Create indexes for common queries
CREATE INDEX idx_site_visits_timestamp ON site_visits(timestamp DESC);
CREATE INDEX idx_site_visits_path ON site_visits(path);
